package com.example.project.model;

import javax.persistence.*;

@Entity
@Table(name = "users")
//These annotations mark the class as a JPA entity and specify the database table name.

public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
//@Id and @GeneratedValue: These annotations indicate that the 'id' field is the primary key and will be auto-generated by the database.
    @Column(unique = true, nullable = false)
    private String username;
//@Column: Specifies column properties, such as uniqueness and nullability, for the 'username' and 'password' fields.
    @Column(nullable = false)
    private String password;

    // ERD Relationships

    // One-to-One relationship with user profile (optional)
    @OneToOne(mappedBy = "user")
    private UserProfile userProfile;
}
