package com.example.project.model;

import javax.persistence.*;

@Entity
@Table(name = "users")
//These annotations mark the class as a JPA entity and specify the database table name.

public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
//@Id and @GeneratedValue: These annotations indicate that the 'id' field is the primary key and will be auto-generated by the database.
    @Column(unique = true, nullable = false)
    private String username;
//@Column: Specifies column properties, such as uniqueness and nullability, for the 'username' and 'password' fields.
    @Column(nullable = false)
    private String password;

    // ERD Relationships

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserProfile getUserProfile() {
        return userProfile;
    }

    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    // One-to-One relationship with user profile (optional)
    @OneToOne(mappedBy = "user")
    private UserProfile userProfile;
}
